### ISSUE TITLE
Fix the server icon

### ISSUE THREAD

**Issue by garentyler** [Unary-Byte-Software/Composition#4]
Currently, the server icon isn't rendered correctly on the client server list. Make it load from a png file, and make the file path dependent on the config.

**Comment by garentyler** [comment]
This should be done after / during Issue #1

**Comment by ghost** [comment]
My client handles the server icon properly, this might require further digging

**Comment by garentyler** [comment]
@khimno Can you provide a screenshot?

**Comment by ghost** [comment]
Disregard my previous message
I am not the brightest at 11pm
